---
{{ if .Values.executor.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "zuul.fullname" . }}-executor
  labels:
{{- include "zuul.executor.labels" . | indent 4 }}
spec:
  serviceName: {{ include "zuul.fullname" . }}-executor
  replicas: {{ .Values.executor.replicas }}
  selector:
    matchLabels:
{{- include "zuul.executor.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{- include "zuul.executor.labels" . | indent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: executor
        image: zuul/zuul-executor:latest
        args:
        - /usr/local/bin/zuul-executor
        - -d
        ports:
        - name: logs
          containerPort: 7900
        volumeMounts:
        - name: zuul-config
          mountPath: /etc/zuul
        securityContext:
          privileged: true
      volumes:
      - name: zuul-config
        secret:
          secretName: {{ include "zuul.fullname" . }}
          defaultMode: 256
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}