---
{{ if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "zuul.fullname" . }}-web
  labels:
{{- include "zuul.web.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
{{- include "zuul.web.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{- include "zuul.web.labels" . | indent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: web
        image: zuul/zuul-web:latest
        args:
        - /usr/local/bin/zuul-web
        - -d
        ports:
        - name: zuul-web
          containerPort: {{ .Values.web.port }}
        volumeMounts:
        - name: zuul-config
          mountPath: /etc/zuul
      volumes:
      - name: zuul-config
        secret:
          secretName: {{ include "zuul.fullname" . }}
          defaultMode: 256
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}